### ISSUE TITLE
Cant Launch it!

### ISSUE THREAD

**Issue by VoxelBuddy** [mhoangvslev/Cubiquity#2]
it keeps crashing for me on 4.14.1 am i doing it wrong? or is it the plugin?

could you make mini tutorial on how to install it so i can check that i'am doing everything correctly?

**Comment by mhoangvslev** [comment]
> it keeps crashing for me on 4.14.1 am i doing it wrong? or is it the plugin?
> could you make mini tutorial on how to install it so i can check that i'am doing everything correctly?

- First you need to download everything and put them under [PROJECTNAME]/Plugins/Cubiquity.
- Generate a solution for Visual Studio and rebuild your project. 
- Copy everything in Content to [PROJECTNAME]/Content/Cubiquity

Kind notes:
- When you put a terrain in a level, scale 100 on every axis and rotate accordingly.
- The trouble we are having now is that the function SculptTerrain make the editor crash and the problem is tracked down to CubiquityC.dll so we recommend you to 4.10 or lower. The original Cubiquity developpers are focusing on Cubiquity2 for recent versions of Unreal Engine.
